version: 2

project_name: gh-depdash

builds:
  - id: gh-depdash
    main: .
    binary: gh-depdash
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: gh-depdash
    ids:
      - gh-depdash
    formats:
      - binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  mode: keep-existing
